# Generated by Django 4.1.3 on 2022-12-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.CharField(max_length=170),
        ),
    ]
